import { Navbar } from '@/components/navbar/NavBar'
import './globals.css'
import { Montserrat } from 'next/font/google'

const mont = Montserrat({ 
  weight: ['300', '400', '500', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Cryptomex',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
